<a href="https://colab.research.google.com/github/dietadestina/datamining_project/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Klasifikasi Risiko Tinggi Putus Sekolah SD Berdasarkan Jenis Kelamin dan Status Sekolah di Indonesia Tahun 2023

In [ ]:
import pandas as pd

# Load dataset
url = "https://raw.githubusercontent.com/dietadestina/datamining_project/refs/heads/main/jumlah-putus-sekolah-menurut-jenis-kelamin-dan-status-sekolah-tiap-provinsi-indonesia-sd-2023.csv"
df = pd.read_csv(url)
df

,Provinsi,Laki-laki (L) - Negeri,Laki-laki (L) - Swasta,Laki-laki (L) - Subjml,Perempuan (P) - Negeri,Perempuan (P) - Swasta,Perempuan (P) - Subjml,Laki-laki dan Perempuan - Negeri,Laki-laki dan Perempuan - Swasta,Laki-laki dan Perempuan - Jumlah
0,Prov. D.K.I. Jakarta,356,100,456,339,74,413,695,174,869
1,Prov. Jawa Barat,2732,327,3059,2348,268,2616,5080,595,5675
2,Prov. Jawa Tengah,1204,126,1330,962,107,1069,2166,233,2399
3,Prov. D.I. Yogyakarta,22,20,42,21,12,33,43,32,75
4,Prov. Jawa Timur,1408,422,1830,1171,326,1497,2579,748,3327
5,Prov. Aceh,417,26,443,429,33,462,846,59,905
6,Prov. Sumatera Utara,1910,453,2363,1599,428,2027,3509,881,4390
7,Prov. Sumatera Barat,481,45,526,300,32,332,781,77,858
8,Prov. Riau,630,149,779,466,143,609,1096,292,1388
9,Prov. Jambi,408,30,438,361,36,397,769,66,835
10,Prov. Sumatera Selatan,1039,82,1121,799,56,855,1838,138,1976
11,Prov. Lampung,394,60,454,316,63,379,710,123,833
12,Prov. Kalimantan Barat,713,68,781,489,54,543,1202,122,1324
13,Prov. Kalimantan Tengah,387,24,411,245,19,264,632,43,675
14,Prov. Kalimantan Selatan,270,22,292,222,18,240,492,40,532
15,Prov. Kalimantan Timur,333,43,376,254,39,293,587,82,669
16,Prov. Sulawesi Utara,169,94,263,104,68,172,273,162,435
17,Prov. Sulawesi Tengah,573,34,607,393,33,426,966,67,1033
18,Prov. Sulawesi Selatan,845,47,892,685,36,721,1530,83,1613
19,Prov. Sulawesi Tenggara,399,16,415,349,20,369,748,36,784
20,Prov. Maluku,399,198,597,317,162,479,716,360,1076
21,Prov. Bali,73,13,86,81,12,93,154,25,179
22,Prov. Nusa Tenggara Barat,591,82,673,498,64,562,1089,146,1235
23,Prov. Nusa Tenggara Timur,921,648,1569,756,446,1202,1677,1094,2771
24,Prov. Papua,209,142,351,185,115,300,394,257,651
25,Prov. Bengkulu,188,27,215,159,16,175,347,43,390
26,Prov. Maluku Utara,286,34,320,281,29,310,567,63,630
27,Prov. Banten,838,96,934,746,99,845,1584,195,1779
28,Prov. Kepulauan Bangka Belitung,201,8,209,112,11,123,313,19,332
29,Prov. Gorontalo,279,7,286,164,8,172,443,15,458
30,Prov. Kepulauan Riau,158,52,210,123,52,175,281,104,385
31,Prov. Papua Barat,156,89,245,145,84,229,301,173,474
32,Prov. Sulawesi Barat,248,35,283,195,33,228,443,68,511
33,Prov. Kalimantan Utara,92,9,101,77,10,87,169,19,188
34,Luar Negeri,45,4,49,36,4,40,81,8,89
35,Prov. Papua Tengah,243,351,594,227,285,512,470,636,1106
36,Prov. Papua Selatan,339,184,523,241,172,413,580,356,936
37,Prov. Papua Pegunungan,413,130,543,295,90,385,708,220,928
38,Prov. Papua Barat Daya,134,61,195,88,51,139,222,112,334

In [ ]:
# Cek semua kolom
df.columns

Index(['Provinsi', 'Laki-laki (L) - Negeri', 'Laki-laki (L) - Swasta',
       'Laki-laki (L) - Subjml', 'Perempuan (P) - Negeri',
       'Perempuan (P) - Swasta', 'Perempuan (P) - Subjml',
       'Laki-laki dan Perempuan - Negeri', 'Laki-laki dan Perempuan - Swasta',
       'Laki-laki dan Perempuan - Jumlah'],
      dtype='object')

In [ ]:
df = df.rename(columns={
    'Laki-laki (L) - Negeri': 'Laki_Negeri',
    'Laki-laki (L) - Swasta': 'Laki_Swasta',
    'Laki-laki (L) - Subjml': 'Jml_Laki',
    'Perempuan (P) - Negeri': 'Perempuan_Negeri',
    'Perempuan (P) - Swasta': 'Perempuan_Swasta',
    'Perempuan (P) - Subjml': 'Jml_Perempuan',
    'Laki-laki dan Perempuan - Jumlah': 'Total_Jumlah'
})

df.columns

Index(['Provinsi', 'Laki_Negeri', 'Laki_Swasta', 'Jml_Laki',
       'Perempuan_Negeri', 'Perempuan_Swasta', 'Jml_Perempuan',
       'Laki-laki dan Perempuan - Negeri', 'Laki-laki dan Perempuan - Swasta',
       'Total_Jumlah'],
      dtype='object')

In [ ]:
# Cek missing values
df.isnull().sum()

Provinsi                            0
Laki_Negeri                         0
Laki_Swasta                         0
Jml_Laki                            0
Perempuan_Negeri                    0
Perempuan_Swasta                    0
Jml_Perempuan                       0
Laki-laki dan Perempuan - Negeri    0
Laki-laki dan Perempuan - Swasta    0
Total_Jumlah                        0
dtype: int64

In [ ]:
df

,Provinsi,Laki_Negeri,Laki_Swasta,Jml_Laki,Perempuan_Negeri,Perempuan_Swasta,Jml_Perempuan,Laki-laki dan Perempuan - Negeri,Laki-laki dan Perempuan - Swasta,Total_Jumlah
0,Prov. D.K.I. Jakarta,356,100,456,339,74,413,695,174,869
1,Prov. Jawa Barat,2732,327,3059,2348,268,2616,5080,595,5675
2,Prov. Jawa Tengah,1204,126,1330,962,107,1069,2166,233,2399
3,Prov. D.I. Yogyakarta,22,20,42,21,12,33,43,32,75
4,Prov. Jawa Timur,1408,422,1830,1171,326,1497,2579,748,3327
5,Prov. Aceh,417,26,443,429,33,462,846,59,905
6,Prov. Sumatera Utara,1910,453,2363,1599,428,2027,3509,881,4390
7,Prov. Sumatera Barat,481,45,526,300,32,332,781,77,858
8,Prov. Riau,630,149,779,466,143,609,1096,292,1388
9,Prov. Jambi,408,30,438,361,36,397,769,66,835
10,Prov. Sumatera Selatan,1039,82,1121,799,56,855,1838,138,1976
11,Prov. Lampung,394,60,454,316,63,379,710,123,833
12,Prov. Kalimantan Barat,713,68,781,489,54,543,1202,122,1324
13,Prov. Kalimantan Tengah,387,24,411,245,19,264,632,43,675
14,Prov. Kalimantan Selatan,270,22,292,222,18,240,492,40,532
15,Prov. Kalimantan Timur,333,43,376,254,39,293,587,82,669
16,Prov. Sulawesi Utara,169,94,263,104,68,172,273,162,435
17,Prov. Sulawesi Tengah,573,34,607,393,33,426,966,67,1033
18,Prov. Sulawesi Selatan,845,47,892,685,36,721,1530,83,1613
19,Prov. Sulawesi Tenggara,399,16,415,349,20,369,748,36,784
20,Prov. Maluku,399,198,597,317,162,479,716,360,1076
21,Prov. Bali,73,13,86,81,12,93,154,25,179
22,Prov. Nusa Tenggara Barat,591,82,673,498,64,562,1089,146,1235
23,Prov. Nusa Tenggara Timur,921,648,1569,756,446,1202,1677,1094,2771
24,Prov. Papua,209,142,351,185,115,300,394,257,651
25,Prov. Bengkulu,188,27,215,159,16,175,347,43,390
26,Prov. Maluku Utara,286,34,320,281,29,310,567,63,630
27,Prov. Banten,838,96,934,746,99,845,1584,195,1779
28,Prov. Kepulauan Bangka Belitung,201,8,209,112,11,123,313,19,332
29,Prov. Gorontalo,279,7,286,164,8,172,443,15,458
30,Prov. Kepulauan Riau,158,52,210,123,52,175,281,104,385
31,Prov. Papua Barat,156,89,245,145,84,229,301,173,474
32,Prov. Sulawesi Barat,248,35,283,195,33,228,443,68,511
33,Prov. Kalimantan Utara,92,9,101,77,10,87,169,19,188
34,Luar Negeri,45,4,49,36,4,40,81,8,89
35,Prov. Papua Tengah,243,351,594,227,285,512,470,636,1106
36,Prov. Papua Selatan,339,184,523,241,172,413,580,356,936
37,Prov. Papua Pegunungan,413,130,543,295,90,385,708,220,928
38,Prov. Papua Barat Daya,134,61,195,88,51,139,222,112,334

##Jenis Kelamin

In [ ]:
#Buat tabel baru
#Tampilkan hanya kolom yang dibutuhkan
do_jk = df[['Provinsi', 'Jml_Laki', 'Jml_Perempuan', 'Total_Jumlah']]
do_jk

                           Provinsi  Jml_Laki  Jml_Perempuan  Total_Jumlah
0              Prov. D.K.I. Jakarta       456            413           869
1                  Prov. Jawa Barat      3059           2616          5675
2                 Prov. Jawa Tengah      1330           1069          2399
3             Prov. D.I. Yogyakarta        42             33            75
4                  Prov. Jawa Timur      1830           1497          3327
5                        Prov. Aceh       443            462           905
6              Prov. Sumatera Utara      2363           2027          4390
7              Prov. Sumatera Barat       526            332           858
8                        Prov. Riau       779            609          1388
9                       Prov. Jambi       438            397           835
10           Prov. Sumatera Selatan      1121            855          1976
11                    Prov. Lampung       454            379           833
12           Prov. Kalimantan Barat       781            543          1324
13          Prov. Kalimantan Tengah       411            264           675
14         Prov. Kalimantan Selatan       292            240           532
15           Prov. Kalimantan Timur       376            293           669
16             Prov. Sulawesi Utara       263            172           435
17            Prov. Sulawesi Tengah       607            426          1033
18           Prov. Sulawesi Selatan       892            721          1613
19          Prov. Sulawesi Tenggara       415            369           784
20                     Prov. Maluku       597            479          1076
21                       Prov. Bali        86             93           179
22        Prov. Nusa Tenggara Barat       673            562          1235
23        Prov. Nusa Tenggara Timur      1569           1202          2771
24                      Prov. Papua       351            300           651
25                   Prov. Bengkulu       215            175           390
26               Prov. Maluku Utara       320            310           630
27                     Prov. Banten       934            845          1779
28  Prov. Kepulauan Bangka Belitung       209            123           332
29                  Prov. Gorontalo       286            172           458
30             Prov. Kepulauan Riau       210            175           385
31                Prov. Papua Barat       245            229           474
32             Prov. Sulawesi Barat       283            228           511
33           Prov. Kalimantan Utara       101             87           188
34                      Luar Negeri        49             40            89
35               Prov. Papua Tengah       594            512          1106
36              Prov. Papua Selatan       523            413           936
37           Prov. Papua Pegunungan       543            385           928
38           Prov. Papua Barat Daya       195            139           334

In [ ]:
# Hitung batas berdasarkan persentil (untuk laki-laki)
q_laki = do_jk['Jml_Laki'].quantile([0.33, 0.66])
q_perempuan = do_jk['Jml_Perempuan'].quantile([0.33, 0.66])
q_total = do_jk['Total_Jumlah'].quantile([0.33, 0.66])

print("Laki-laki:\n", q_laki)
print("\nPerempuan:\n", q_perempuan)
print("\nTotal:\n", q_total)

Laki-laki:
 0.33    307.12
0.66    594.24
Name: Jml_Laki, dtype: float64

Perempuan:
 0.33    252.96
0.66    463.36
Name: Jml_Perempuan, dtype: float64

Total:
 0.33     584.92
0.66    1036.44
Name: Total_Jumlah, dtype: float64

In [ ]:
# Fungsi klasifikasi berdasarkan kuartil
def label_kuartil(val, batas1, batas2):
    if val <= batas1:
        return 'Rendah'
    elif val <= batas2:
        return 'Sedang'
    else:
        return 'Tinggi'

# Terapkan ke masing-masing kolom
do_jk['Risiko_Laki'] = do_jk['Jml_Laki'].apply(lambda x: label_kuartil(x, q_laki[0.33], q_laki[0.66]))
do_jk['Risiko_Perempuan'] = do_jk['Jml_Perempuan'].apply(lambda x: label_kuartil(x, q_perempuan[0.33], q_perempuan[0.66]))
do_jk['Risiko_Total'] = do_jk['Total_Jumlah'].apply(lambda x: label_kuartil(x, q_total[0.33], q_total[0.66]))

/tmp/ipython-input-122-1930582649.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  do_jk['Risiko_Laki'] = do_jk['Jml_Laki'].apply(lambda x: label_kuartil(x, q_laki[0.33], q_laki[0.66]))
/tmp/ipython-input-122-1930582649.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  do_jk['Risiko_Perempuan'] = do_jk['Jml_Perempuan'].apply(lambda x: label_kuartil(x, q_perempuan[0.33], q_perempuan[0.66]))
/tmp/ipython-input-122-1930582649.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  do_jk['Risiko_Total'] = do_jk['Total_Jumlah'].apply(lambda x: label_kuartil(x, q_total[0.33], q_total[0.66]))

In [ ]:
# Lihat distribusi label baru
print("Distribusi Risiko Laki-laki:")
print(do_jk['Risiko_Laki'].value_counts())
print("\nDistribusi Risiko Perempuan:")
print(do_jk['Risiko_Perempuan'].value_counts())
print("\nDistribusi Risiko Total:")
print(do_jk['Risiko_Total'].value_counts())

Distribusi Risiko Laki-laki:
Risiko_Laki
Sedang    13
Tinggi    13
Rendah    13
Name: count, dtype: int64

Distribusi Risiko Perempuan:
Risiko_Perempuan
Sedang    13
Tinggi    13
Rendah    13
Name: count, dtype: int64

Distribusi Risiko Total:
Risiko_Total
Sedang    13
Tinggi    13
Rendah    13
Name: count, dtype: int64

In [ ]:
do_jk

,Provinsi,Jml_Laki,Jml_Perempuan,Total_Jumlah,Risiko_Laki,Risiko_Perempuan,Risiko_Total
0,Prov. D.K.I. Jakarta,456,413,869,Sedang,Sedang,Sedang
1,Prov. Jawa Barat,3059,2616,5675,Tinggi,Tinggi,Tinggi
2,Prov. Jawa Tengah,1330,1069,2399,Tinggi,Tinggi,Tinggi
3,Prov. D.I. Yogyakarta,42,33,75,Rendah,Rendah,Rendah
4,Prov. Jawa Timur,1830,1497,3327,Tinggi,Tinggi,Tinggi
5,Prov. Aceh,443,462,905,Sedang,Sedang,Sedang
6,Prov. Sumatera Utara,2363,2027,4390,Tinggi,Tinggi,Tinggi
7,Prov. Sumatera Barat,526,332,858,Sedang,Sedang,Sedang
8,Prov. Riau,779,609,1388,Tinggi,Tinggi,Tinggi
9,Prov. Jambi,438,397,835,Sedang,Sedang,Sedang
10,Prov. Sumatera Selatan,1121,855,1976,Tinggi,Tinggi,Tinggi
11,Prov. Lampung,454,379,833,Sedang,Sedang,Sedang
12,Prov. Kalimantan Barat,781,543,1324,Tinggi,Tinggi,Tinggi
13,Prov. Kalimantan Tengah,411,264,675,Sedang,Sedang,Sedang
14,Prov. Kalimantan Selatan,292,240,532,Rendah,Rendah,Rendah
15,Prov. Kalimantan Timur,376,293,669,Sedang,Sedang,Sedang
16,Prov. Sulawesi Utara,263,172,435,Rendah,Rendah,Rendah
17,Prov. Sulawesi Tengah,607,426,1033,Tinggi,Sedang,Sedang
18,Prov. Sulawesi Selatan,892,721,1613,Tinggi,Tinggi,Tinggi
19,Prov. Sulawesi Tenggara,415,369,784,Sedang,Sedang,Sedang
20,Prov. Maluku,597,479,1076,Tinggi,Tinggi,Tinggi
21,Prov. Bali,86,93,179,Rendah,Rendah,Rendah
22,Prov. Nusa Tenggara Barat,673,562,1235,Tinggi,Tinggi,Tinggi
23,Prov. Nusa Tenggara Timur,1569,1202,2771,Tinggi,Tinggi,Tinggi
24,Prov. Papua,351,300,651,Sedang,Sedang,Sedang
25,Prov. Bengkulu,215,175,390,Rendah,Rendah,Rendah
26,Prov. Maluku Utara,320,310,630,Sedang,Sedang,Sedang
27,Prov. Banten,934,845,1779,Tinggi,Tinggi,Tinggi
28,Prov. Kepulauan Bangka Belitung,209,123,332,Rendah,Rendah,Rendah
29,Prov. Gorontalo,286,172,458,Rendah,Rendah,Rendah
30,Prov. Kepulauan Riau,210,175,385,Rendah,Rendah,Rendah
31,Prov. Papua Barat,245,229,474,Rendah,Rendah,Rendah
32,Prov. Sulawesi Barat,283,228,511,Rendah,Rendah,Rendah
33,Prov. Kalimantan Utara,101,87,188,Rendah,Rendah,Rendah
34,Luar Negeri,49,40,89,Rendah,Rendah,Rendah
35,Prov. Papua Tengah,594,512,1106,Sedang,Tinggi,Tinggi
36,Prov. Papua Selatan,523,413,936,Sedang,Sedang,Sedang
37,Prov. Papua Pegunungan,543,385,928,Sedang,Sedang,Sedang
38,Prov. Papua Barat Daya,195,139,334,Rendah,Rendah,Rendah

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Encode label klasifikasi
le = LabelEncoder()
do_jk['Label_Laki'] = le.fit_transform(do_jk['Risiko_Laki'])
do_jk['Label_Perempuan'] = le.fit_transform(do_jk['Risiko_Perempuan'])

# Cek hasil encoding
print(le.classes_)
do_jk

['Rendah' 'Sedang' 'Tinggi']

/tmp/ipython-input-125-1408580492.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  do_jk['Label_Laki'] = le.fit_transform(do_jk['Risiko_Laki'])
/tmp/ipython-input-125-1408580492.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  do_jk['Label_Perempuan'] = le.fit_transform(do_jk['Risiko_Perempuan'])

,Provinsi,Jml_Laki,Jml_Perempuan,Total_Jumlah,Risiko_Laki,Risiko_Perempuan,Risiko_Total,Label_Laki,Label_Perempuan
0,Prov. D.K.I. Jakarta,456,413,869,Sedang,Sedang,Sedang,1,1
1,Prov. Jawa Barat,3059,2616,5675,Tinggi,Tinggi,Tinggi,2,2
2,Prov. Jawa Tengah,1330,1069,2399,Tinggi,Tinggi,Tinggi,2,2
3,Prov. D.I. Yogyakarta,42,33,75,Rendah,Rendah,Rendah,0,0
4,Prov. Jawa Timur,1830,1497,3327,Tinggi,Tinggi,Tinggi,2,2
5,Prov. Aceh,443,462,905,Sedang,Sedang,Sedang,1,1
6,Prov. Sumatera Utara,2363,2027,4390,Tinggi,Tinggi,Tinggi,2,2
7,Prov. Sumatera Barat,526,332,858,Sedang,Sedang,Sedang,1,1
8,Prov. Riau,779,609,1388,Tinggi,Tinggi,Tinggi,2,2
9,Prov. Jambi,438,397,835,Sedang,Sedang,Sedang,1,1
10,Prov. Sumatera Selatan,1121,855,1976,Tinggi,Tinggi,Tinggi,2,2
11,Prov. Lampung,454,379,833,Sedang,Sedang,Sedang,1,1
12,Prov. Kalimantan Barat,781,543,1324,Tinggi,Tinggi,Tinggi,2,2
13,Prov. Kalimantan Tengah,411,264,675,Sedang,Sedang,Sedang,1,1
14,Prov. Kalimantan Selatan,292,240,532,Rendah,Rendah,Rendah,0,0
15,Prov. Kalimantan Timur,376,293,669,Sedang,Sedang,Sedang,1,1
16,Prov. Sulawesi Utara,263,172,435,Rendah,Rendah,Rendah,0,0
17,Prov. Sulawesi Tengah,607,426,1033,Tinggi,Sedang,Sedang,2,1
18,Prov. Sulawesi Selatan,892,721,1613,Tinggi,Tinggi,Tinggi,2,2
19,Prov. Sulawesi Tenggara,415,369,784,Sedang,Sedang,Sedang,1,1
20,Prov. Maluku,597,479,1076,Tinggi,Tinggi,Tinggi,2,2
21,Prov. Bali,86,93,179,Rendah,Rendah,Rendah,0,0
22,Prov. Nusa Tenggara Barat,673,562,1235,Tinggi,Tinggi,Tinggi,2,2
23,Prov. Nusa Tenggara Timur,1569,1202,2771,Tinggi,Tinggi,Tinggi,2,2
24,Prov. Papua,351,300,651,Sedang,Sedang,Sedang,1,1
25,Prov. Bengkulu,215,175,390,Rendah,Rendah,Rendah,0,0
26,Prov. Maluku Utara,320,310,630,Sedang,Sedang,Sedang,1,1
27,Prov. Banten,934,845,1779,Tinggi,Tinggi,Tinggi,2,2
28,Prov. Kepulauan Bangka Belitung,209,123,332,Rendah,Rendah,Rendah,0,0
29,Prov. Gorontalo,286,172,458,Rendah,Rendah,Rendah,0,0
30,Prov. Kepulauan Riau,210,175,385,Rendah,Rendah,Rendah,0,0
31,Prov. Papua Barat,245,229,474,Rendah,Rendah,Rendah,0,0
32,Prov. Sulawesi Barat,283,228,511,Rendah,Rendah,Rendah,0,0
33,Prov. Kalimantan Utara,101,87,188,Rendah,Rendah,Rendah,0,0
34,Luar Negeri,49,40,89,Rendah,Rendah,Rendah,0,0
35,Prov. Papua Tengah,594,512,1106,Sedang,Tinggi,Tinggi,1,2
36,Prov. Papua Selatan,523,413,936,Sedang,Sedang,Sedang,1,1
37,Prov. Papua Pegunungan,543,385,928,Sedang,Sedang,Sedang,1,1
38,Prov. Papua Barat Daya,195,139,334,Rendah,Rendah,Rendah,0,0

###Laki-laki

In [ ]:
from sklearn.model_selection import train_test_split

# Fitur dan target laki-laki
X_laki = do_jk[['Jml_Laki']]
y_laki = do_jk['Label_Laki']

# Split data
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_laki, y_laki, test_size=0.2, stratify=y_laki, random_state=42
)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_l, y_train_l)
y_pred_dt = dt.predict(X_test_l)

print("=== Decision Tree - Laki-laki ===")
print(classification_report(y_test_l, y_pred_dt, target_names=le.classes_))

=== Decision Tree - Laki-laki ===
              precision    recall  f1-score   support

      Rendah       1.00      1.00      1.00         2
      Sedang       0.75      1.00      0.86         3
      Tinggi       1.00      0.67      0.80         3

    accuracy                           0.88         8
   macro avg       0.92      0.89      0.89         8
weighted avg       0.91      0.88      0.87         8

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_l, y_train_l)
y_pred_knn = knn.predict(X_test_l)

print("=== KNN - Laki-laki ===")
print(classification_report(y_test_l, y_pred_knn, target_names=le.classes_))

=== KNN - Laki-laki ===
              precision    recall  f1-score   support

      Rendah       1.00      1.00      1.00         2
      Sedang       0.75      1.00      0.86         3
      Tinggi       1.00      0.67      0.80         3

    accuracy                           0.88         8
   macro avg       0.92      0.89      0.89         8
weighted avg       0.91      0.88      0.87         8

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train_l, y_train_l)
y_pred_nb = nb.predict(X_test_l)

print("=== Naive Bayes - Laki-laki ===")
print(classification_report(y_test_l, y_pred_nb, target_names=le.classes_))

=== Naive Bayes - Laki-laki ===
              precision    recall  f1-score   support

      Rendah       1.00      1.00      1.00         2
      Sedang       0.75      1.00      0.86         3
      Tinggi       1.00      0.67      0.80         3

    accuracy                           0.88         8
   macro avg       0.92      0.89      0.89         8
weighted avg       0.91      0.88      0.87         8

###Perempuan

In [ ]:
# Fitur dan target Perempuan
X_perempuan = do_jk[['Jml_Perempuan']]
y_perempuan = do_jk['Label_Perempuan']

# Split data
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_perempuan, y_perempuan, test_size=0.2, stratify=y_perempuan, random_state=42
)

In [ ]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_l, y_train_l)
y_pred_dt = dt.predict(X_test_l)

print("=== Decision Tree - Perempuan ===")
print(classification_report(y_test_l, y_pred_dt, target_names=le.classes_))

=== Decision Tree - Perempuan ===
              precision    recall  f1-score   support

      Rendah       1.00      1.00      1.00         2
      Sedang       1.00      1.00      1.00         3
      Tinggi       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_l, y_train_l)
y_pred_knn = knn.predict(X_test_l)

print("=== KNN - Perempuan ===")
print(classification_report(y_test_l, y_pred_knn, target_names=le.classes_))

=== KNN - Perempuan ===
              precision    recall  f1-score   support

      Rendah       1.00      1.00      1.00         2
      Sedang       1.00      1.00      1.00         3
      Tinggi       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

In [ ]:
nb = GaussianNB()
nb.fit(X_train_l, y_train_l)
y_pred_nb = nb.predict(X_test_l)

print("=== Naive Bayes - Perempuan ===")
print(classification_report(y_test_l, y_pred_nb, target_names=le.classes_))

=== Naive Bayes - Perempuan ===
              precision    recall  f1-score   support

      Rendah       1.00      1.00      1.00         2
      Sedang       1.00      1.00      1.00         3
      Tinggi       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

##Status Sekolah